apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esewa-testing.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "esewa-testing.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
